name: Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Copy google-services.json
      run:  cp ./app/google-services.example.json google-services.json
    - name: Build with Gradle
      run: ./gradlew build
